[package]
name = "blockchain"
version = "0.1.0"
authors = ["Adam Szalkowski <adam@szalkowski.de>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
iron = "0.6"
rayon = "0.9"
rustc-serialize = "0.3"
router = "0.6"
sha2 = "0.6"
time = "0.1"
tokio-core = "0.1"
